- _id: TASK-001
  name: "Design Homepage Mockups"
  project: "PROJ-001"
  due_date: "2024-12-31"
  completed: false

- _id: TASK-002
  name: "Setup CI/CD Pipeline"
  project: "PROJ-001"
  due_date: "2024-11-15"
  completed: true

- _id: TASK-003
  name: "Draft App Requirements"
  project: "PROJ-002"
  due_date: "2025-01-20"
  completed: false

- _id: TASK-004
  name: "Choose Tech Stack"
  project: "PROJ-002"
  due_date: "2025-01-10"
  completed: true
